# [START gae_quickstart_yaml]
runtime: nodejs14

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /login
    static_files: build/index.html
    upload: build/index.html

  - url: /static
    #static_dir: ../frontend/build/
    static_dir: build/static/
    #upload: ~/imgrows-blbi/frontend/build/index.html

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

# [END gae_quickstart_yaml]
